### ISSUE TITLE
v3.2.0 release

### ISSUE THREAD

**Issue by ozmartian** [UnitedRPMs/vidcutter#3]
hi guys!

I've updated the spec for the latest 3.2.0 release.. Travis didn't do its thing after my commit was pushed so can you guys gets this updated in the repo, when you have a moment to spare :-)

much appreciated!

**Comment by kuboosoft** [comment]
Hi @ozmartian  Do you want join to the project? I can add you as official maintainer of vidcuter. I only need add unibuild tool for vidcutter repository and  your update is uploaded directly to the cloud, y next syncing with the repository;  our tools make the magic.

**Comment by ozmartian** [comment]
thanks for that... you can make me maintainer if that helps you guys out, no problem. i will add it to my list to ensure it is updated with each future release...

thanks again

**Comment by kuboosoft** [comment]
@ozmartian Welcome to team!! Only accept the invitation :)
